name: Build and Publish Docker Images

on:
  schedule:
    - cron: '0 3 * * *'
  release:
    types: [published]
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]
    # Only build the image when a file in the image is updated
    # These paths are files in the git repository from
    # .dockerignore (except the Docker files)
    paths-ignore:
      - ".devcontainer/**"
      - ".editorconfig"
      - ".github/**"
      - "!.github/workflows/docker.yml" # Still run on changes to this file
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "**.md"
      - "config.example.json"
      - "LICENSE"
      - "pyproject.toml"
      - "setup.cfg"
      - "tests/**"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
              # set latest tag for default branch
              type=raw,value=latest,enable={{is_default_branch}}
              # set main tag for default branch
              type=raw,value=main,enable={{is_default_branch}}
          
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
